------------------------------------------------------------
-- 06_sentiment_scoring.sql
-- Use Cortex AI functions to score sentiment on TECH_NEWS
------------------------------------------------------------

USE DATABASE CRYPTO_SENTIMENT_DB;
USE SCHEMA ANALYTICS;

UPDATE CRYPTO_SENTIMENT_DB.ANALYTICS.TECH_NEWS
SET
  SENTIMENT_SCORE = SNOWFLAKE.CORTEX.SENTIMENT(CONTENT),
  SENTIMENT_LABEL = CASE
    WHEN SNOWFLAKE.CORTEX.SENTIMENT(CONTENT) >  0.3 THEN 'POSITIVE'
    WHEN SNOWFLAKE.CORTEX.SENTIMENT(CONTENT) < -0.3 THEN 'NEGATIVE'
    ELSE 'NEUTRAL'
  END
WHERE SENTIMENT_SCORE IS NULL;

SELECT
  SEARCH_TERM,
  COUNT(*)                              AS ARTICLE_COUNT,
  ROUND(AVG(SENTIMENT_SCORE), 3)        AS AVG_SENTIMENT,
  SUM(CASE WHEN SENTIMENT_LABEL = 'POSITIVE' THEN 1 ELSE 0 END) AS POSITIVE_COUNT,
  SUM(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 ELSE 0 END) AS NEGATIVE_COUNT,
  SUM(CASE WHEN SENTIMENT_LABEL = 'NEUTRAL'  THEN 1 ELSE 0 END) AS NEUTRAL_COUNT
FROM CRYPTO_SENTIMENT_DB.ANALYTICS.TECH_NEWS
GROUP BY SEARCH_TERM
ORDER BY AVG_SENTIMENT DESC;

